---
title: "Brownlows Bets"
author: "Your Name Goes Here"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"    
    
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
require(tigerstats)
require(knitr)
source(file="BrLw.R")
```


<!-- We recommend you use git branches -- create a separate branch for each major section i.e. Introduction, Methods, Results, Inferential Results, and Discussion and Conclusions - leave the YAML block untouched until the final merge where you put in your own name !-->

# Introduction

<!--In this section you explain what you are trying to show.  Where did the data come from?  What is the research or other question you are trying to answer?!-->

 At the first day of class there are 35 students in Math Statistics class.  Professor Brownlow always proposes this bet to his students "I will wager $1 to your bet of $1 that at least two people in this class have  the same birthday (Month, Day).  Use ChatGPT to write an Rmarkdown file that uses simulation to answer these three questions

## 1
Given a class size of 35, what is the probability Dr. J wins the bet?   Assume 25 of the 35 students take the bet, what is Dr. J's expected profit/loss? Draw a histogram of the simulated probabilities.  What is a 95% confidence interval for the estimated probability of a Dr.J win?

## 2
Suppose class size were 26 students, instead of 35. With the same bet ($1 to $1) What is the probability Dr. J wins the bet now?   Assume 20 of the 26 students take the bet, how much is Dr. J's expected profit/loss now?

## 3
What size class (how many students) makes the $1 against $1 bet fair?  



# Discussion and Conclusion

<!--Discussion and conclusion here.  If professor Brownlow is consistantly making or losing money how could he change his payout so that his profits center on zero?  Also discuss what size his class should be in order to have his current scheme balance at zero profit.!-->

